In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
churn_df=pd.read_csv("../data/teleco_customer_churn_train.csv")

In [3]:
churn_df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
churn_df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [5]:
churn_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [6]:
numeric_cols=churn_df.select_dtypes(include=["int64", "float64"]).columns
categorical_cols=churn_df.select_dtypes(include=["object"]).columns
print("Number of numeric_cols:",len(numeric_cols))
print("Number of categorical_cols:",len(categorical_cols))

Number of numeric_cols: 3
Number of categorical_cols: 18

In [7]:
numeric_cols

Index(['SeniorCitizen', 'tenure', 'MonthlyCharges'], dtype='object')

In [8]:
categorical_cols

Index(['customerID', 'gender', 'Partner', 'Dependents', 'PhoneService',
       'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup',
       'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
       'Contract', 'PaperlessBilling', 'PaymentMethod', 'TotalCharges',
       'Churn'],
      dtype='object')

In [9]:
# Converting TotalCharges column from categorical to numeric

churn_df["TotalCharges"]=pd.to_numeric(churn_df["TotalCharges"], errors="coerce")

In [10]:
churn_df["TotalCharges"].isnull().sum()

11

In [11]:
churn_df=churn_df.dropna()

In [12]:
churn_df["TotalCharges"].isnull().sum()

0

In [13]:
churn_df=churn_df.drop(columns=["customerID"])

In [14]:
churn_df["SeniorCitizen"].unique()

array([0, 1], dtype=int64)

In [15]:
churn_df.shape

(7032, 20)

In [16]:
# Wrote this line again because the categorical_cols still contains customerID column as this line is execued before
categorical_cols=churn_df.select_dtypes(include=["object"]).columns

In [17]:
numeric_cols=churn_df.select_dtypes(include=["int64", "float64"]).columns
categorical_cols=churn_df.select_dtypes(include=["object"]).columns
print("Number of numeric_cols:",len(numeric_cols))
print("Number of categorical_cols:",len(categorical_cols))

Number of numeric_cols: 4
Number of categorical_cols: 16

In [18]:
for col in categorical_cols:
    print(f"{col}: {churn_df[col].unique()}")

gender: ['Female' 'Male']
Partner: ['Yes' 'No']
Dependents: ['No' 'Yes']
PhoneService: ['No' 'Yes']
MultipleLines: ['No phone service' 'No' 'Yes']
InternetService: ['DSL' 'Fiber optic' 'No']
OnlineSecurity: ['No' 'Yes' 'No internet service']
OnlineBackup: ['Yes' 'No' 'No internet service']
DeviceProtection: ['No' 'Yes' 'No internet service']
TechSupport: ['No' 'Yes' 'No internet service']
StreamingTV: ['No' 'Yes' 'No internet service']
StreamingMovies: ['No' 'Yes' 'No internet service']
Contract: ['Month-to-month' 'One year' 'Two year']
PaperlessBilling: ['Yes' 'No']
PaymentMethod: ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
Churn: ['No' 'Yes']

In [19]:
for col in numeric_cols:
    print(f"{col}: {churn_df[col].unique()}")

SeniorCitizen: [0 1]
tenure: [ 1 34  2 45  8 22 10 28 62 13 16 58 49 25 69 52 71 21 12 30 47 72 17 27
  5 46 11 70 63 43 15 60 18 66  9  3 31 50 64 56  7 42 35 48 29 65 38 68
 32 55 37 36 41  6  4 33 67 23 57 61 14 20 53 40 59 24 44 19 54 51 26 39]
MonthlyCharges: [29.85 56.95 53.85 ... 63.1  44.2  78.7 ]
TotalCharges: [  29.85 1889.5   108.15 ...  346.45  306.6  6844.5 ]

In [20]:
# Converting SeniorCitizen column from numeric to categorical

churn_df["SeniorCitizen"]=churn_df["SeniorCitizen"].astype("object")

In [21]:
numeric_cols=churn_df.select_dtypes(include=["int64", "float64"]).columns
categorical_cols=churn_df.select_dtypes(include=["object"]).columns
print("Number of numeric_cols:",len(numeric_cols))
print("Number of categorical_cols:",len(categorical_cols))

Number of numeric_cols: 3
Number of categorical_cols: 17

In [22]:
numeric_cols

Index(['tenure', 'MonthlyCharges', 'TotalCharges'], dtype='object')

In [23]:
categorical_cols

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'PhoneService',
       'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup',
       'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
       'Contract', 'PaperlessBilling', 'PaymentMethod', 'Churn'],
      dtype='object')

In [24]:
binary_cols = [
    "Partner",
    "Dependents",
    "PhoneService",
    "PaperlessBilling"
]

for col in binary_cols:
    churn_df[col] = churn_df[col].replace({"Yes":1, "No":0})
churn_df["gender"] = churn_df["gender"].replace({"Female":1, "Male":0})

In [25]:
for col in categorical_cols:
    print(f"{col}: {churn_df[col].unique()}")

gender: [1 0]
SeniorCitizen: [0 1]
Partner: [1 0]
Dependents: [0 1]
PhoneService: [0 1]
MultipleLines: ['No phone service' 'No' 'Yes']
InternetService: ['DSL' 'Fiber optic' 'No']
OnlineSecurity: ['No' 'Yes' 'No internet service']
OnlineBackup: ['Yes' 'No' 'No internet service']
DeviceProtection: ['No' 'Yes' 'No internet service']
TechSupport: ['No' 'Yes' 'No internet service']
StreamingTV: ['No' 'Yes' 'No internet service']
StreamingMovies: ['No' 'Yes' 'No internet service']
Contract: ['Month-to-month' 'One year' 'Two year']
PaperlessBilling: [1 0]
PaymentMethod: ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
Churn: ['No' 'Yes']

In [26]:
from sklearn.preprocessing import OneHotEncoder

multiple_cols=['InternetService', 
    'Contract', 
    'PaymentMethod',
    "OnlineSecurity",
    "OnlineBackup",
    "DeviceProtection",
    "TechSupport",
    "StreamingTV",
    "StreamingMovies",
    "MultipleLines"
]
churn_df = churn_df.reset_index(drop=True)
encoder= OneHotEncoder(sparse_output=False, handle_unknown='ignore')
for col in multiple_cols:
    encoder.fit(churn_df[[col]])
    encoded = encoder.transform(churn_df[[col]])
    encoded_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out([col]), index=churn_df.index)
    churn_df = pd.concat([churn_df, encoded_df], axis=1)
    churn_df = churn_df.drop(columns=[col])

In [27]:
churn_df.shape

(7032, 41)

In [28]:
target_column = "Churn"
inputs = churn_df.drop(columns=[target_column])
target = churn_df[target_column]

In [29]:
inputs

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,InternetService_DSL,...,TechSupport_Yes,StreamingTV_No,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No,StreamingMovies_No internet service,StreamingMovies_Yes,MultipleLines_No,MultipleLines_No phone service,MultipleLines_Yes
0,1,0,1,0,1,0,1,29.85,29.85,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,0,0,0,0,34,1,0,56.95,1889.50,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2,0,0,0,0,2,1,1,53.85,108.15,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
3,0,0,0,0,45,0,0,42.30,1840.75,1.0,...,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,1,0,0,0,2,1,1,70.70,151.65,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,0,0,1,1,24,1,1,84.80,1990.50,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
7028,1,0,1,1,72,1,1,103.20,7362.90,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
7029,1,0,1,1,11,0,1,29.60,346.45,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
7030,0,1,1,0,4,1,1,74.40,306.60,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
7031,0,0,0,0,66,1,1,105.65,6844.50,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0

In [31]:
inputs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 40 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   gender                                   7032 non-null   int64
 1   SeniorCitizen                            7032 non-null   object
 2   Partner                                  7032 non-null   int64
 3   Dependents                               7032 non-null   int64
 4   tenure                                   7032 non-null   int64
 5   PhoneService                             7032 non-null   int64
 6   PaperlessBilling                         7032 non-null   int64
 7   MonthlyCharges                           7032 non-null   float64
 8   TotalCharges                             7032 non-null   float64
 9   InternetService_DSL                      7032 non-null   float64
 10  InternetService_Fiber optic              7032 non-null   float64
 11  InternetService_No                       7032 non-null   float64
 12  Contract_Month-to-month                  7032 non-null   float64
 13  Contract_One year                        7032 non-null   float64
 14  Contract_Two year                        7032 non-null   float64
 15  PaymentMethod_Bank transfer (automatic)  7032 non-null   float64
 16  PaymentMethod_Credit card (automatic)    7032 non-null   float64
 17  PaymentMethod_Electronic check           7032 non-null   float64
 18  PaymentMethod_Mailed check               7032 non-null   float64
 19  OnlineSecurity_No                        7032 non-null   float64
 20  OnlineSecurity_No internet service       7032 non-null   float64
 21  OnlineSecurity_Yes                       7032 non-null   float64
 22  OnlineBackup_No                          7032 non-null   float64
 23  OnlineBackup_No internet service         7032 non-null   float64
 24  OnlineBackup_Yes                         7032 non-null   float64
 25  DeviceProtection_No                      7032 non-null   float64
 26  DeviceProtection_No internet service     7032 non-null   float64
 27  DeviceProtection_Yes                     7032 non-null   float64
 28  TechSupport_No                           7032 non-null   float64
 29  TechSupport_No internet service          7032 non-null   float64
 30  TechSupport_Yes                          7032 non-null   float64
 31  StreamingTV_No                           7032 non-null   float64
 32  StreamingTV_No internet service          7032 non-null   float64
 33  StreamingTV_Yes                          7032 non-null   float64
 34  StreamingMovies_No                       7032 non-null   float64
 35  StreamingMovies_No internet service      7032 non-null   float64
 36  StreamingMovies_Yes                      7032 non-null   float64
 37  MultipleLines_No                         7032 non-null   float64
 38  MultipleLines_No phone service           7032 non-null   float64
 39  MultipleLines_Yes                        7032 non-null   float64
dtypes: float64(33), int64(6), object(1)
memory usage: 2.1+ MB